title: Misa Engine Page
description: A blog and website for the Misa Engine.
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
plugins:
- jekyll-remote-theme
- jekyll-sass-converter
- jekyll-include-cache

show_downloads: true
