# Basic site settings
title: "Misa Engine"
description: "A brief description of your project."
baseurl: ""
url: "https://case-presley.github.io" # Replace with your actual GitHub Pages URL

# Theme
remote_theme: "mmistakes/minimal-mistakes"

# Plugins for GitHub Pages
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

# Navigation
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "single"

# Author Information
author:
  name: "Your Name"
  avatar: "/assets/images/avatar.png"
  bio: "A short bio about you."
  location: "Your Location"
  email: "your-email@example.com"

# Social Links
social:
  - name: GitHub
    url: "https://github.com/case-presley"
    icon: "fab fa-github"

# Enable Collections
collections:
  docs:
    output: true


minimal_mistakes_skin: "dark"
repository: "case-presley/Misa-Engine"
logo: /assets/images/not88x88.jpg