package misa.tiled2misa;

import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.NodeList;

import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import java.io.File;
import java.io.InputStream;
import java.nio.ByteBuffer;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * This class is used for loading and parsing TMX files generated by the Tiled map editor.
 * It extracts map attributes, tilesets, layers, and object layers to create a TiledMap object.
 */
@SuppressWarnings("unused")
public class TiledParser
{
    private static final Logger LOGGER = Logger.getLogger(TiledParser.class.getName());

    private String resourceBasePath = "";

    public void setResourceBasePath(String basePath)
    {
        if (!basePath.endsWith("/"))
        {
            basePath += "/";
        }
        this.resourceBasePath = basePath;
    }

    public TiledMap loadFromTMX(String filePath)
    {
        try
        {
            File xmlFile = new File(filePath);
            Document document = parseXMLFile(xmlFile);
            return createTiledMapFromDocument(document);
        }
        catch (Exception e)
        {
            LOGGER.severe("Failed to load map from TMX: " + filePath);
            return null;
        }
    }

    public TiledMap loadFromInputStream(InputStream inputStream)
    {
        try
        {
            Document document = parseXMLStream(inputStream);
            LOGGER.info("Successfully parsed XML document from InputStream.");
            return createTiledMapFromDocument(document);
        }
        catch (Exception e)
        {
            LOGGER.log(Level.SEVERE, "Failed to load map from InputStream.", e);
            return null;
        }
    }

    private Document parseXMLFile(File file) throws Exception
    {
        DocumentBuilderFactory dbFactory = DocumentBuilderFactory.newInstance();
        DocumentBuilder documentBuilder = dbFactory.newDocumentBuilder();
        Document document = documentBuilder.parse(file);
        document.getDocumentElement().normalize();
        return document;
    }

    private Document parseXMLStream(InputStream inputStream) throws Exception
    {
        DocumentBuilderFactory dbFactory = DocumentBuilderFactory.newInstance();
        DocumentBuilder documentBuilder = dbFactory.newDocumentBuilder();
        Document document = documentBuilder.parse(inputStream);
        document.getDocumentElement().normalize();
        LOGGER.info("XML parsing completed successfully.");
        return document;
    }

    private TiledMap createTiledMapFromDocument(Document document)
    {
        Element mapElement = document.getDocumentElement();
        int mapWidth = getIntAttribute(mapElement, "width");
        int mapHeight = getIntAttribute(mapElement, "height");
        int tileWidth = getIntAttribute(mapElement, "tilewidth");
        int tileHeight = getIntAttribute(mapElement, "tileheight");

        List<TiledTileset> tilesets = parseTilesets(document);
        List<TiledLayer> layers = parseLayers(document);
        List<TiledObject> objects = parseObjectLayers(document);

        return new TiledMap.Builder()
                .setWidth(mapWidth)
                .setHeight(mapHeight)
                .setTileWidth(tileWidth)
                .setTileHeight(tileHeight)
                .setLayers(layers)
                .setTilesets(tilesets)
                .setObjects(objects)
                .build();
    }

    private int getIntAttribute(Element element, String attribute)
    {
        try
        {
            return Integer.parseInt(element.getAttribute(attribute));
        }
        catch (NumberFormatException e)
        {
            LOGGER.warning("Invalid integer attribute: " + attribute);
            return 0;
        }
    }

    private List<TiledTileset> parseTilesets(Document document)
    {
        List<TiledTileset> tilesets = new ArrayList<>();
        NodeList tilesetNodes = document.getElementsByTagName("tileset");

        for (int i = 0; i < tilesetNodes.getLength(); i++)
        {
            Element tilesetElement = (Element) tilesetNodes.item(i);
            String source = tilesetElement.getAttribute("source");
            int firstGID = getIntAttribute(tilesetElement, "firstgid");

            String tsxPath = resourceBasePath + source;
            String imagePath = extractImagePathFromTSX(tsxPath);

            if (imagePath != null)
            {
                tilesets.add(new TiledTileset(imagePath, firstGID));
                LOGGER.info("Successfully loaded tileset: " + tsxPath + " (image: " + imagePath + ")");
            }
        }
        return tilesets;
    }

    private String extractImagePathFromTSX(String tsxPath)
    {
        try (InputStream tsxStream = getClass().getClassLoader().getResourceAsStream(tsxPath))
        {
            if (tsxStream == null)
            {
                LOGGER.severe("Failed to find .tsx file: " + tsxPath);
                return null;
            }

            DocumentBuilderFactory dbFactory = DocumentBuilderFactory.newInstance();
            DocumentBuilder documentBuilder = dbFactory.newDocumentBuilder();
            Document document = documentBuilder.parse(tsxStream);

            Element imageElement = (Element) document.getElementsByTagName("image").item(0);
            return resourceBasePath + imageElement.getAttribute("source");
        }
        catch (Exception e)
        {
            LOGGER.log(Level.SEVERE, "Failed to parse .tsx file: " + tsxPath, e);
            return null;
        }
    }

    private List<TiledLayer> parseLayers(Document document)
    {
        List<TiledLayer> layers = new ArrayList<>();
        NodeList layerNodes = document.getElementsByTagName("layer");

        for (int i = 0; i < layerNodes.getLength(); i++)
        {
            Element layerElement = (Element) layerNodes.item(i);
            String layerName = layerElement.getAttribute("name");
            int layerWidth = getIntAttribute(layerElement, "width");
            int layerHeight = getIntAttribute(layerElement, "height");

            LOGGER.info("Parsing layer: " + layerName);

            Element dataElement = (Element) layerElement.getElementsByTagName("data").item(0);
            String encoding = dataElement.getAttribute("encoding");
            long[][] tileData;

            try
            {
                if ("csv".equalsIgnoreCase(encoding))
                {
                    tileData = decodeCSVTileData(dataElement.getTextContent().trim(), layerWidth, layerHeight);
                }
                else if ("base64".equalsIgnoreCase(encoding))
                {
                    tileData = decodeBase64TileData(dataElement.getTextContent().trim(), layerWidth, layerHeight);
                }
                else
                {
                    LOGGER.warning("Unsupported encoding: " + encoding + " for layer: " + layerName);
                    continue;
                }

                layers.add(new TiledLayer(layerName, layerWidth, layerHeight, tileData));
            }
            catch (Exception e)
            {
                LOGGER.log(Level.SEVERE, "Failed to parse layer: " + layerName, e);
            }
        }
        return layers;
    }

    private long[][] decodeCSVTileData(String csvData, int width, int height)
    {
        long[][] tileData = new long[height][width];
        String[] tokens = csvData.split(",");

        for (int row = 0; row < height; row++)
        {
            for (int col = 0; col < width; col++)
            {
                int index = row * width + col;
                tileData[row][col] = Long.parseLong(tokens[index].trim());
            }
        }
        return tileData;
    }

    private long[][] decodeBase64TileData(String encodedData, int width, int height)
    {
        byte[] decodedData = Base64.getDecoder().decode(encodedData);
        ByteBuffer buffer = ByteBuffer.wrap(decodedData);
        long[][] tileData = new long[height][width];

        for (int row = 0; row < height; row++)
        {
            for (int col = 0; col < width; col++)
            {
                tileData[row][col] = buffer.getInt() & 0xFFFFFFFFL;
            }
        }
        return tileData;
    }

    private List<TiledObject> parseObjectLayers(Document document)
    {
        List<TiledObject> objects = new ArrayList<>();
        NodeList objectGroupNodes = document.getElementsByTagName("objectgroup");

        for (int i = 0; i < objectGroupNodes.getLength(); i++)
        {
            Element objectGroupElement = (Element) objectGroupNodes.item(i);
            NodeList objectNodes = objectGroupElement.getElementsByTagName("object");

            for (int j = 0; j < objectNodes.getLength(); j++)
            {
                Element objectElement = (Element) objectNodes.item(j);
                objects.add(getObject(objectElement));
            }
        }
        return objects;
    }

    private static TiledObject getObject(Element objectElement)
    {
        int id = Integer.parseInt(objectElement.getAttribute("id"));
        String name = objectElement.hasAttribute("name") ? objectElement.getAttribute("name") : "Unnamed";
        String type = objectElement.hasAttribute("type") ? objectElement.getAttribute("type") : "Undefined";
        double x = Double.parseDouble(objectElement.getAttribute("x"));
        double y = Double.parseDouble(objectElement.getAttribute("y"));
        double width = objectElement.hasAttribute("width") ?
                Double.parseDouble(objectElement.getAttribute("width")) : 0;
        double height = objectElement.hasAttribute("height") ?
                Double.parseDouble(objectElement.getAttribute("height")) : 0;

        Map<String, String> properties = new HashMap<>();
        NodeList propertyNodes = objectElement.getElementsByTagName("property");
        for (int p = 0; p < propertyNodes.getLength(); p++)
        {
            Element propertyElement = (Element) propertyNodes.item(p);
            properties.put(propertyElement.getAttribute("name"), propertyElement.getAttribute("value"));
        }

        return new TiledObject(id, name, type, x, y, width, height, properties);
    }
}
